version: '3.7'
services:
  db:
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: comments
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  db2:
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: news
    ports:
      - "5434:5432"
    volumes:
      - db_data2:/var/lib/postgresql/data

volumes:
  db_data:
  db_data2:
